home/urls.py
from django.conf.urls import url
from . import views

app_name='home'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
    url(r'album/add/$',views.AlbumCreate.as_view(),name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(), name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(), name='album-delete'),]
      

my/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', admin.site.urls),
url(r'^home/',include('home.urls')),
]

if settings.DEBUG:
     urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=250)
    album_logo=models.FileField()
    
    def get_absolute_url(self):
        return reverse('home-detail', kwargs={'pk': self.pk}) 
  
class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    song_title=models.CharField(max_length=250,default=' ')
    is_fav=models.BooleanField(default=False)
        

home/views.py
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views import generic
from .models import Album
from django.urls import reverse_lazy

class IndexView(generic.ListView):
     template_name = 'home/index.html'
     context_object_name='all_albums'  

     def get_queryset(self):
           return Album.objects.all() 

class DetailView(generic.DetailView):
     template_name = 'home/details.html' 
     model=Album
        


class AlbumCreate(CreateView):
      
     model=Album
     fields=['artist','album_title']
     
class AlbumUpdate(UpdateView):
     model=Album
     fields=['artist','album_title']

class AlbumDelete(DeleteView):
     model=Album
     success_url=reverse_lazy('home:index')        
     

home/templates/home/album_form.html
{% extends 'home/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}
{% block body %}
<div class="container-fluid">

<div class="row">
<div class="col-sm-12 col-md-7">
<div class="panel panel-defult">
<div class="panel-body">
<form class="form-horizontal" action="{% url 'home:index' %}" method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {% include 'home/form-template.html' %}
            <div class="form-group">
             <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                   </div>
 </form>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{% block title %}Viberrr{% endblock %}</title>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
<div class="container-fluid">

<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle=" collapse" data-target="#topNavBar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{% url 'home:index' %}">Viberrr</a>
</div>

<div class="collapse navbar-collapse">
<ul class="nav navbar-nav">
<li class=" ">
<a href="{% url 'home:index' %}">
<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Album</a>
</li>

<li class=" ">
<a href="">
<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs</a>
</li>
</ul>

<form class="navbar-form navbar-left" role="search" method="get" action=" ">
<div class="from-group">
<input type="text" class="form-control" name="q" value=" ">

<button type="submit" class="btn btn-default">Search</button>
</div></form>

<ul class="nav navbar-nav navbar-right">
<li class=" ">
<a href="{% url 'home:album-add' %}">
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album</a>
</li>

<li class=" ">
<a href="">
<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;LogOut</a>
</li>
</ul>

</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

home/templates/home/details.html
{% extends 'home/base.html' %}


{% block title %}Album Details{% endblock %}

{% block body %}

     {% for song in album.song_set.all%}

              
                 {{ song.song_title}}<br>
            
     {% endfor%}
 
{% endblock %}

home/templates/home/form-template.html
{% for field in form %}
    <div class="form-group">
    <div class=" col-sm-offset-2 col-sm-10">
    <span class="text-danger small">{{ field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block body %}


    <ul>
             {% for album in all_albums %}
                 <li><a href="{% url 'home:detail' album.id %}">{{album.album_title}}</a></li>
                   <img src="{{album.album_logo.url}}">
                   <form action="{% url 'home:album-delete' album.id %}" method="post" style="display:inline;">
                     {% csrf_token %}
                    <button type="submit" class="btn-btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                        </button>
                        </form>             
            
             {% endfor %}  
    </ul>



{% endblock %}